### ISSUE TITLE
TCPTransport never reconnects after a socket error, causing infinite Errno 110 loop

### ISSUE THREAD

**Issue by ekmi64** [matfroh/abl_emh1_modbus#20]
I encountered this problem in my HA environment and resolved it using the AI tool Claude. Claude suggested opening an issue so that more users might benefit from the solution. Here is the Claude issue:

When the TCP connection to the RS485-to-Ethernet converter (e.g. a Protoss PE11) 
drops for any reason, the integration never detects it and keeps trying to write 
to the dead socket forever. This produces thousands of repeated log entries like:

Error reading current: [Errno 110] Operation timed out
socket.send() raised exception.
Error sending wake-up sequence: [Errno 110] Operation timed out

The integration never recovers on its own — only a full Home Assistant restart 
fixes it.

**Root cause**
In `modbus_device.py`, `TCPTransport.write()` does not catch `OSError`/
`ConnectionError` raised by `writer.drain()`. When it fails, `self.is_connected` 
stays `True`, so every subsequent poll keeps calling `write()` on the same 
broken socket instead of reconnecting.

```python
async def write(self, data: bytes):
    if not self.is_connected:
        raise ConnectionError("TCP connection not open.")
    self.writer.write(data)
    await self.writer.drain()   # <- exception here doesn't reset is_connected
```

The same issue exists in `readline()` and in `SerialTransport`.

**Suggested fix**
- Catch `OSError`/`ConnectionError` in `write()`/`readline()` in both 
  `TCPTransport` and `SerialTransport`, set `self.is_connected = False` and 
  close the writer.
- Add an `_ensure_connected()` helper on `ModbusASCIIDevice` that reopens the 
  transport if it isn't open, called at the start of every public method 
  (`read_current`, `send_raw_command`, `wake_up_device`, `write_current`, etc.), 
  with a small backoff to avoid hammering an unreachable device every poll.

I have a working patch for this (happy to open a PR) — it restored stable 
polling for me after a connection drop, no more manual restarts needed.

**Environment**
- Integration version: 2.1.3
- Connection: TCP via Protoss PE11 (RS485-to-Ethernet)
- Home Assistant: 2026.8.3

[modbus_device.py](https://github.com/user-attachments/files/31722735/modbus_device.py)

**Comment by matfroh** [comment]
@ekmi64 Thanks for spotting and patching, PR welcomed!

**Comment by ekmi64** [comment]
Follow-up to my report above. After deploying the initial reconnect patch, 
I noticed the socket-error-based reconnect works correctly (confirmed in logs: 
`Transport for X.X.X.X:502 not open, attempting to reconnect...` fires as 
expected on actual `OSError`/`Errno 110`).

However, there's a second failure mode that the original patch doesn't catch: 
the TCP session can go **silently stale** — the socket stays "open" from 
Python's point of view (no exception on write, no `OSError`), but the device 
simply stops answering. Symptom in the log:

Invalid or incomplete response: None


...repeating hundreds/thousands of times, with no accompanying connection 
error. I confirmed this is not a wiring/device issue: querying the wallbox 
directly with a separate Modbus tool during the same failure window still 
got valid responses, while the integration kept getting empty reads.

**Suggested addition to the fix:** track consecutive empty/invalid responses 
in `ModbusASCIIDevice` (I used a threshold of 5) and force-close the 
transport when the threshold is hit, even without a socket exception. The 
existing reconnect-on-open path then rebuilds the connection on the next 
poll. A single successful read resets the counter, so normal transient 
timeouts don't trigger an unnecessary reconnect.

I have this working as an extension of my earlier patch — happy to combine 
both into one PR if useful.

[modbus_device.py](https://github.com/user-attachments/files/31773559/modbus_device.py)

**Comment by DerAutomatiker** [comment]
Hi @ekmi64 I was facing the same issues and implemented your changes in my systems. I will keep you updated if I find an error.

**Comment by matfroh** [comment]
Please go ahead and draft the PR. On my end I can only test modbus RS486 and will see if it creates other issues

**Comment by DerAutomatiker** [comment]
Applying this patch (modbus_device.py with the ModbusASCIITransport/SerialTransport/TCPTransport abstraction) fixes the reconnect loop, but it introduces a follow-on regression in __init__.py: async_unload_entry still references the old device.serial attribute, which no longer exists on ModbusASCIIDevice after this refactor. The connection is now held in self.transport instead.

This breaks manual reloads (e.g. via an automation that calls homeassistant.reload_config_entry after a connection drop):

```
Logger: homeassistant.config_entries
Error unloading entry ABL eMH1 for ev_charger_modbus
Traceback (most recent call last):
  File "/config/custom_components/ev_charger_modbus/__init__.py", line 282, in async_unload_entry
    if device.serial.is_open:
       ^^^^^^^^^^^^^
AttributeError: 'ModbusASCIIDevice' object has no attribute 'serial'
```

Because async_unload_entry raises before the connection is ever closed, the serial port / TCP socket is left open. A subsequent reload then can't reopen it, and only a full Home Assistant restart clears it — this made the reconnect fix from this issue not fully effective for me until I also patched __init__.py.

Fix — update async_unload_entry in __init__.py to use the new transport attribute instead of serial, and don't let a close failure abort the whole unload:

```
async def async_unload_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Unload a config entry."""
    if unload_ok := await hass.config_entries.async_unload_platforms(entry, PLATFORMS):
        device = hass.data[DOMAIN][entry.entry_id]["device"]

        # ModbusASCIIDevice no longer exposes "self.serial" after the
        # transport-abstraction refactor; the connection (serial OR TCP)
        # now lives in "self.transport" (SerialTransport / TCPTransport),
        # which provides an is_open property and a close() method.
        try:
            transport = getattr(device, "transport", None)
            if transport is not None and transport.is_open:
                transport.close()
                _LOGGER.debug(
                    "Closed transport for entry %s during unload", entry.entry_id
                )
        except Exception as err:  # pragma: no cover
            # Don't let a failure while closing the connection abort
            # the whole unload/reload.
            _LOGGER.warning(
                "Error closing connection during unload: %s", err
            )

        hass.data[DOMAIN].pop(entry.entry_id)
    return unload_ok
```

With this in place, reload-after-connection-loss (which this issue's fix is meant to support) actually works end-to-end without requiring a full HA restart. Tested against v2.1.3 + the patch from this issue.

**Comment by matfroh** [comment]
thanks @ekmi64 and @DerAutomatiker , I truly value your contribution!
It would be really great if you could you the PR function, it simplifies a lot ;-) 
Both your proposition are now merged in the main code and will be released in the next version.

**Comment by DerAutomatiker** [comment]
I'll try to think myself into the PR function. I'm more the user atm but will try my best :)
Thanks for changing the code!

**Comment by petervandiepen** [comment]
Confirming fix in v2.1.4 — issue #20 (connection reset retry-loop) and options flow crash

With help of Claude, I was able to sort this out

Setup: ABL EMH1 charger connected via a Waveshare RS485-to-Ethernet gateway (TCP Server mode, port 4196), integration v2.1.3 → v2.1.4.

Before updating, I consistently hit the retry-loop described in #20: after a full charging cycle completed (EV fully charged), the integration would spam Error reading current: [Errno 104] Connection reset by peer and Error sending wake-up sequence in a tight loop with no backoff — one log capture reached 760,000+ lines / ~45MB within a few hours. Reloading the integration didn't help; it also threw AttributeError: 'ModbusASCIIDevice' object has no attribute 'serial' during unload, so the retry loop kept running until a full Home Assistant restart. I had to temporarily exclude the charger's entities from the recorder to stop the database from filling up.

Separately, opening the integration's options ("Configure") threw a 500 Internal Server Error, traced to self.config_entry = config_entry in EVChargerModbusOptionsFlow.__init__ conflicting with the read-only config_entry property on newer HA core versions.

After updating to v2.1.4 (PRs #22 and #23), both issues are resolved on the first pass: the options page opens correctly, and reload/unload no longer crashes. I'll keep monitoring across a few more charge cycles to confirm the reconnect logic holds up long-term, but wanted to confirm early that the fix appears to work for a Waveshare TCP gateway setup specifically — thanks for the quick turnaround!
